#!/usr/bin/env python3
"""
Claude Code Notification smart dispatcher.
Plays different sounds based on notification_type in the hook payload.
Auto-generated by /set-notification skill.
"""
import json
import random
import subprocess
import sys

SOUNDS = "/System/Library/Sounds"

# idle_prompt: random StarCraft Terran unit quote
STARCRAFT_IDLE = [
    "It's a wonderful day!",                                    # SCV
    "I'm locked in here with a bunch of perverts!",            # SCV
    "What, you ran out of Marines?",                           # SCV
    "You want a piece of me, boy?",                            # Marine
    "How do I get out of this chicken-shit outfit?",           # Marine
    "I come in peace... usually.",                             # Marine
    "I'm about to drop the hammer and dispense some justice!", # Siege Tank
    "I love the smell of singed Zerg in the morning.",         # Siege Tank
    "Abandon ship! Dammit, can't find the buttons!",           # Battlecruiser
    "I see dead people.",                                      # Ghost
    "Nuclear launch detected.",                                # Ghost
    "The doctor is in.",                                       # Medic
    "I've already diagnosed your condition... INFECTED!",      # Medic
]

# notification_type → (sound file stem, say phrase)
TYPE_MAP = {
    "permission_prompt":  ("Hero", "Permission Need"),
    "elicitation_dialog": ("Hero", "Confirmation Need"),
    "idle_prompt":        ("Funk", random.choice(STARCRAFT_IDLE)),
}
DEFAULT = ("Funk", "Attention Need")

try:
    data = json.load(sys.stdin)
    ntype = data.get("notification_type", "")
except Exception:
    ntype = ""

sound, phrase = TYPE_MAP.get(ntype, DEFAULT)

subprocess.Popen(["afplay", f"{SOUNDS}/{sound}.aiff"], stderr=subprocess.DEVNULL)
subprocess.Popen(["say", phrase])
